### ISSUE TITLE
View item (5)

### ISSUE THREAD

**Issue by BioTurboNick** [scottx611x/csci-e71-term-project#10]
As a School Administrator, I want to be able to view an item in the inventory so that I can see all the equipment we own.

I want to be able to see all of the properties of a given item.

This user story also applies to these stakeholders: IT Personnel

Tasks:
- [x] Write tests for retrieving items to database - Nick/Scott
- [x] Write code to retrieving item to database - Nick/Scott
- [x] Make a item view with all fields - Rob
- [x] Integrate parts - Sri

**Comment by BioTurboNick** [comment]
Tasks:
- [ ] Write tests for retrieving items to database - Nick/Scott
- [ ] Write code to retrieving item to database - Nick/Scott
- [ ] Make a item view with all fields - Rob
- [ ] Integrate parts - Sri

**Comment by scottx611x** [comment]
Closed as of https://github.com/scottx611x/csci-e71-term-project/commit/529e20f2e9229322b39cc9d5f02a11c39928de1d
