### ISSUE TITLE
Refactor Controller's index methods

### ISSUE THREAD

**Issue by scottx611x** [scottx611x/csci-e71-term-project#19]
I see a lot of duplicate code like this: https://github.com/scottx611x/csci-e71-term-project/blob/master/app-context/app/Http/Controllers/ComputerController.php#L10-L22 in our controllers.

Maybe we could have our Controllers extend a base Controller with this similar functionality?

A refactor like this could also bump our code coverage way up

**Comment by BioTurboNick** [comment]
Closing b/c unable to do given Laravel framework's reliance on static methods and lack of generic types in PHP.
